# Generated by Django 4.2.6 on 2023-10-17 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'About', 'verbose_name_plural': 'Abouts'},
        ),
        migrations.AlterModelOptions(
            name='feature',
            options={'verbose_name': 'Feature', 'verbose_name_plural': 'Features'},
        ),
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name': 'Home', 'verbose_name_plural': 'Homes'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Menu', 'verbose_name_plural': 'Menues'},
        ),
        migrations.AlterModelOptions(
            name='menu_category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='home',
            name='banner',
        ),
        migrations.AlterField(
            model_name='about',
            name='about_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='about',
            name='article',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='about',
            name='article_author',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='about',
            name='descriptions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='left_image',
            field=models.ImageField(blank=True, upload_to='about/left_image/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='icons',
            field=models.ImageField(blank=True, upload_to='Feature/icons/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='sub_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='feature',
            name='title',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.menu_category'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='food_image',
            field=models.ImageField(blank=True, upload_to='Menu/food_image/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='food_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='menu',
            name='food_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='menu',
            name='icons',
            field=models.ImageField(blank=True, upload_to='Menu/icons/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='sub_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='menu',
            name='title',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='menu_category',
            name='icons',
            field=models.ImageField(blank=True, upload_to='Menu_Category/icons/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='menu_category',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
