# Generated by Django 4.2.6 on 2023-10-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_about_options_alter_feature_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icons', models.ImageField(blank=True, upload_to='Events/icons/%Y/%m/%d')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('title_card', models.CharField(blank=True, max_length=255)),
                ('book_card', models.DateTimeField(auto_now_add=True)),
                ('description_card', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.AddField(
            model_name='home',
            name='banner',
            field=models.ImageField(default=5, upload_to='media/banner/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
